---
title: "project"
author: "Jordan Stump"
date: "2024-04-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
test_df = read_csv("madison2024.csv", col_names = c("date", "location", "temp", "vis"))
test_df$temp = test_df$temp / 10
test_df$vis = as.numeric(test_df$vis) * 1
test_df$date <- as.Date(test_df$date)
test_df <- subset(test_df, temp != 999.9)


train_df = read_csv("madisonTrain.csv", col_names = c("date", "location", "temp", "vis"))
train_df$temp = train_df$temp / 10
train_df$vis = as.numeric(train_df$vis) * 1
train_df$date <- as.Date(train_df$date)
train_df <- subset(train_df, temp != 999.9)

```

```{r}
test_series_temp = test_df %>% group_by(date) %>% summarise(daily_max = max(temp))
ggplot(test_series, aes(x = date, y = daily_max)) +
  geom_line() +
  geom_point() +  # Add points
  labs(x = "Date", y = "Daily Maximum Temperature") +
  ggtitle("Daily Maximum Temperature Time Series with Points")
```


```{r}
train_series_temp = train_df %>% group_by(date) %>% summarise(daily_max = max(temp))
ggplot(train_series, aes(x = date, y = daily_max)) +
  geom_line() +
  geom_point() +  # Add points
  labs(x = "Date", y = "Daily Maximum Temperature") +
  ggtitle("Daily Maximum Temperature Time Series with Points")
```



```{r}
test_series_vis = test_df %>% group_by(date) %>% summarise(daily_max = max(vis))
ggplot(test_series_vis, aes(x = date, y = daily_max)) +
  geom_line() +
  geom_point() +  # Add points
  labs(x = "Date", y = "Daily Maximum Visability") +
  ggtitle("Daily Maximum Visability Time Series with Points")
```


```{r}
train_series_vis = train_df %>% group_by(date) %>% summarise(daily_max = max(vis))
ggplot(train_series_vis, aes(x = date, y = daily_max)) +
  geom_line() +
  geom_point() +  # Add points
  labs(x = "Date", y = "Daily Maximum Visability") +
  ggtitle("Daily Maximum Visability Time Series with Points")
```











